name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Black
        run: black --check .
      - name: Flake8
        run: flake8
      - name: Mypy
        run: mypy .
      - name: Pytest
        run: pytest
 - name: Package Lambda
        run: zip -j process_scan.zip lambda/process_scan/*
      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload Lambda artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: aws s3 cp process_scan.zip s3://${{ secrets.LAMBDA_S3_BUCKET }}/process_scan.zip
